theme: jekyll-theme-minimal
title: Banji Ajibade - Cybersecurity Portfolio
description: Certified Ethical Hacker and IT Professional with expertise in Microsoft 365 security, penetration testing, and GDPR compliance.
